### ISSUE TITLE
Jump to editor when loading a file

### ISSUE THREAD

**Issue by ascheman** [ahus1/asciidoc-editor#13]
As a user I would like to jump to the editor if I load a URL (pressing the return key or the load button) in order to make work more smooth (otherwise I seem to have to select the file from the loaded files afterwards).

**Comment by ahus1** [comment]
When #14 is fixed, the load button will jump to the editor; there was an error that interrupted loading in mid-flight. Will leave this open to add keyboard interaction.

**Comment by ahus1** [comment]
The editor received a form to enter the different parts of in a real form. Submission now possible using ENTER once all fields are filled.

![image](https://user-images.githubusercontent.com/3957921/96183839-d40a6100-0f37-11eb-8275-856996d121dd.png)
