### ISSUE TITLE
Cannot save to my own repository

### ISSUE THREAD

**Issue by ascheman** [ahus1/asciidoc-editor#14]
Having loaded a file from my own repository and being logged in
![image](https://user-images.githubusercontent.com/456000/84619925-d5b71000-aed6-11ea-8756-acd3a4ed1f4b.png)

I cannot save changes to the file:
![image](https://user-images.githubusercontent.com/456000/84619897-bc15c880-aed6-11ea-8752-868e61a198d4.png)

**Comment by ahus1** [comment]
Stupid me, I was tricked by using only existing files. Now tested and fixed when adding a new file.
