### ISSUE TITLE
URL-API

### ISSUE THREAD

**Issue by rdmueller** [ahus1/asciidoc-editor#15]
I would like to use the editor by just prepending its url to a document.

Example:

I am currently viewing the README on Github at 

    https://github.com/ahus1/asciidoc-editor/blob/master/README.adoc

I would like to edit it in the asciidoc-editor by prepending `https://asciidoc-editor.ahus1.de#` to get

    https://asciidoc-editor.ahus1.de#https://github.com/ahus1/asciidoc-editor/blob/master/README.adoc
.
This would make it super easy to use it in the same way as gitpod.

**Comment by ahus1** [comment]
This already works with the slightly longer URL

```
http://localhost:8080/#/edit?file=https://github.com/ahus1/asciidoc-editor/blob/master/README.adoc
```

Will look after it that the shorter variant will work as well.

**Comment by ahus1** [comment]
(updated previous comment with a non-localhost link)

**Comment by ahus1** [comment]
The next version supports the shorter URL as suggested
