### ISSUE TITLE
Document don't load in Safari

### ISSUE THREAD

**Issue by abelsromero** [ahus1/asciidoc-editor#67]
Same url working fine in other browsers (Firefox & Chrome) does not load in Safari.
A white screen is shown and the following error appears in the console.

![image](https://user-images.githubusercontent.com/5781153/122989965-b5504a00-d3a3-11eb-883e-a30c8d464a3d.png)

**Comment by ahus1** [comment]
This might be this problem: https://github.com/sindresorhus/normalize-url/issues/105
I'll investigate

**Comment by ahus1** [comment]
I found that this is instead related to Asciidoctor Kroki that is not Safari-compatible at the moment. 
I'll skip the Asciidoctor Kroki functionality in Safari until this is fixed. 

I tested it using a online browser test service successfully. I'll have a new version deployed tomorrow.

https://github.com/Mogztter/asciidoctor-kroki/issues/225

**Comment by Mogztter** [comment]
@ahus1 I don't have Safari at hand, could you please confirm that https://github.com/Mogztter/asciidoctor-kroki/pull/228 fixes this issue?

**Comment by ahus1** [comment]
Hi  @Mogztter - finally found a way to test it for me (as a non-mac owner); got myself a 30 day subscription at https://www.lambdatest.com/ to test this and other things related to Safari. 

Works great!
